name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "before printing the folder contents"
      run: ls
    - uses: actions/checkout@v4
    - name: "after printing the folder contents"
      run: ls -a
